#!/bin/bash
# Install the MLX model server for the current user. Safe to re-run.
# Usage: server/setup.sh [--home DIR] [--model REPO] [--hf-home DIR] [--port 8080] [--no-download]
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
SERVER_HOME="$HOME/mlx-worker-server"
MODEL="mlx-community/Qwen3.8-27B-4bit"
HF_DIR=""
PORT=8080
DOWNLOAD=1
while [[ $# -gt 0 ]]; do
  case "$1" in
    --home) SERVER_HOME="$2"; shift 2 ;;
    --model) MODEL="$2"; shift 2 ;;
    --hf-home) HF_DIR="$2"; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    --no-download) DOWNLOAD=0; shift ;;
    -h|--help) sed -n '2,3p' "$0"; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done
HF_DIR="${HF_DIR:-$SERVER_HOME/hf}"

"$HERE/preflight.sh" --port "$PORT" || { echo "fix the failures above, then re-run" >&2; exit 1; }

# Pick the first native arm64 Python 3.11+
PY=""
for candidate in python3.13 python3.12 python3.11 python3; do
  path="$(command -v "$candidate" 2>/dev/null)" || continue
  if "$path" -c 'import sys, platform; sys.exit(0 if sys.version_info >= (3, 11) and platform.machine() == "arm64" else 1)' 2>/dev/null; then
    PY="$path"; break
  fi
done

mkdir -p "$SERVER_HOME/logs" "$HF_DIR/hub"
if [[ ! -x "$SERVER_HOME/venv/bin/python" ]]; then
  echo "creating virtual environment with $PY"
  "$PY" -m venv "$SERVER_HOME/venv"
fi
"$SERVER_HOME/venv/bin/python" -m pip install -q --upgrade pip
"$SERVER_HOME/venv/bin/python" -m pip install -q --upgrade 'mlx-lm>=0.31.3' huggingface_hub

# Configuration the start script and launch agent source
cat > "$SERVER_HOME/env.sh" <<ENV
# Generated by mlx-worker server/setup.sh. Source it; do not execute it.
export MLX_MODEL="$MODEL"
export MLX_PORT="$PORT"
export HF_HOME="$HF_DIR"
export HF_HUB_CACHE="$HF_DIR/hub"
# Public models need no login, and a stale stored token can cause 401 errors.
export HF_HUB_DISABLE_IMPLICIT_TOKEN=1
ENV
cp "$HERE/start.sh" "$SERVER_HOME/start.sh"
chmod +x "$SERVER_HOME/start.sh"

if [[ $DOWNLOAD -eq 1 ]]; then
  echo "downloading $MODEL (skips files already in the cache)"
  # shellcheck source=/dev/null
  source "$SERVER_HOME/env.sh"
  "$SERVER_HOME/venv/bin/hf" download "$MODEL" >/dev/null
fi

"$SERVER_HOME/venv/bin/python" -m pip freeze > "$SERVER_HOME/requirements-known-good.txt"
echo
echo "installed in $SERVER_HOME"
echo "start it now:        $SERVER_HOME/start.sh"
echo "or at every login:   $HERE/launchagent.sh install --home $SERVER_HOME"
echo "then share it:       $HERE/serve.sh --port $PORT"
